---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible-lint-config.json
profile: production

exclude_paths:
  - .github/

skip_list:
  - yaml[line-length]

...
