#:schema https://mise.jdx.dev/schema/mise.json

[tools]
node = "24"
prek = "0.5.2"
uv = "0.12.10"

"pipx:ansible-core" = { version = "2.21.3", uvx_args = "--with docker --with requests" }
"pipx:ansible-doctor" = { version= "8.4.1", uvx_args = "--with ansible-core" }
"pipx:ansible-lint" = "26.8.0"
"pipx:molecule" = { version = "26.8.0", uvx_args = "--with molecule-hetznercloud --with molecule-plugins[docker] --with pytest --with pytest-testinfra --with-executables-from pytest" }
